import { BaseRepository } from './base.repository.js';
import {
  CoursesRepository,
  DEFAULT_FAQS,
  DEFAULT_LEGAL,
  DEFAULT_PLANS,
  MemoryFallbackRepository,
  UsersRepository
} from './live.repository.js';

export const repos = {
  users: new UsersRepository(),
  refreshTokens: new MemoryFallbackRepository('refresh_tokens'),
  passwordResets: new MemoryFallbackRepository('password_resets'),
  userSettings: new MemoryFallbackRepository('user_settings'),
  deviceTokens: new MemoryFallbackRepository('device_tokens'),
  courses: new CoursesRepository(),
  groups: new MemoryFallbackRepository('groups'),
  classes: new MemoryFallbackRepository('classes'),
  subjects: new BaseRepository('subjects'),
  chapters: new BaseRepository('chapters'),
  lessons: new MemoryFallbackRepository('lessons'),
  content: new MemoryFallbackRepository('study_materials'),
  videos: new MemoryFallbackRepository('video_lectures'),
  currentAffairs: new MemoryFallbackRepository('current_affairs'),
  bookmarks: new MemoryFallbackRepository('bookmarks'),
  tests: new BaseRepository('tests'),
  questions: new BaseRepository('questions'),
  attempts: new MemoryFallbackRepository('test_attempts'),
  answers: new MemoryFallbackRepository('test_answers'),
  results: new MemoryFallbackRepository('test_results'),
  progress: new MemoryFallbackRepository('user_progress'),
  activity: new MemoryFallbackRepository('user_activity'),
  lessonCompletions: new MemoryFallbackRepository('lesson_completions'),
  plans: new MemoryFallbackRepository('plans', DEFAULT_PLANS),
  subscriptions: new BaseRepository('subscriptions'),
  payments: new BaseRepository('payments'),
  faqs: new MemoryFallbackRepository('faq', DEFAULT_FAQS),
  tickets: new BaseRepository('support_tickets'),
  messages: new MemoryFallbackRepository('support_messages'),
  legal: new MemoryFallbackRepository('legal_documents', DEFAULT_LEGAL),
  notifications: new BaseRepository('notifications'),
  students: new BaseRepository('students'),
  admins: new BaseRepository('admins')
};
